### ISSUE TITLE
Make Secondary Menu/Links Accessible to Client

### ISSUE THREAD

**Issue by rcass** [redacademy/sosnpr-fall-2017#10]
Looking at about-us.php, proposed-park.php and resources.php they all seem to have these secondary menu/links or banner menus but done differently on each template.
For example on proposer-park.php they are calling the CFS field labels and then in about-us.php they are just hard coded.

I recommend that you just go with one method. Even better would be making these link customizable to the client, so aka registering some menus.

Check this out for more info[codex](https://codex.wordpress.org/Function_Reference/register_nav_menus)

[here](https://generatewp.com/nav-menus/) is a generator as well

**Comment by qingxin-yuan** [comment]
The page nav menu is now uniformly hard coded - custom menu method will be in the future consideration.

Thanks for pointing it out!
