### ISSUE TITLE
Remove number Class Names (ex: "one"), use nth selectors!

### ISSUE THREAD

**Issue by rcass** [redacademy/sosnpr-fall-2017#11]
In proposed-park.php i noticed the used of class names such as "one", "two", "three", etc.

If you are using these to target you should be using more descriptive classes or if this just for CSS targeting I highly recommend just getting smart with child selectors in css rather than adding more markup.

More info read [this](https://css-tricks.com/almanac/selectors/n/nth-child/)

**Comment by michaelujkim** [comment]
closed by colin mj

**Comment by rcass** [comment]
Not quite closed, I see the class names have changed to `class="content-container-one" ` and `essay-content-1` . Basically if we find we are just using class names to essentially count divs, it prob not the best solution. 

Many of these files really do have an excess of divs. I would try to remove many of them, turn a div into something more semantic (ex:article) when necessary. Then when styling use nth-type, to apply styles to a certain one (ex: 
```
article:nth-of-type(2) {
    background: red;
}

```
