### ISSUE TITLE
Up Navigation Arrows need additional CSS for when pressed

### ISSUE THREAD

**Issue by rcass** [redacademy/sosnpr-fall-2017#12]
They look  a bit broken when pressed, just need to recenter the triange/icon perhaps

![screen shot 2017-12-14 at 2 40 53 pm](https://user-images.githubusercontent.com/5028555/34017998-f7af2b5e-e0dc-11e7-85e2-608b2b8447e1.png)

**Comment by qingxin-yuan** [comment]
Issue resolved! 
Cheers

**Comment by rcass** [comment]
Sorry to be so nit picky, but they are still off:
Here are picks between unclicked and clicked:
![screen shot 2017-12-15 at 11 06 33 am](https://user-images.githubusercontent.com/5028555/34056517-258072b2-e188-11e7-8f9e-22d4725ab0c2.png)
![screen shot 2017-12-15 at 11 06 26 am](https://user-images.githubusercontent.com/5028555/34056521-2b1b5fac-e188-11e7-8a6c-1bd9238e1bb8.png)

Just looks kinda off. If it moved slightly upward it would look like a feature, but the way it move downward just makes it look slightly broken.

Also I just noticed this, but for accessibility and making ti obvious those are clickable, add a hover state. I recommend just darken (see sass mixin for darken) on hover.

**Comment by qingxin-yuan** [comment]
Sorry forgot to deploy. Now it looks good on the staging site!
Cheers
