### ISSUE TITLE
Find a client accessible solution to PDF

### ISSUE THREAD

**Issue by rcass** [redacademy/sosnpr-fall-2017#13]
In proposed-park.php the link to the pdf is only found in the php template. This is going to make it really difficult for the client to ever change.

Also, if the uploads folder ever changes, this will prob result in a 404 for the pdf

here is the code in question:
```
 <a href="<?php echo get_site_url() . '/wp-content/uploads/2017/12/sos_economicreport_lr.pdf'?>"><div class="pdf-container">
              <p>Download Full Report </p>
```

Create a solution that can be accessed by the client

**Comment by michaelujkim** [comment]
done by Colin MJ!

**Comment by rcass** [comment]
Most certainly a step in the right direction, but I think this still requires some tweaking.

Concerns:
* Is this always going to be a pdf?  If so I would change the field to just a file upload rather than WYSIWYG, since putting in text kinda breaks your design.
* Place this field before the FAQ, so it matches the visual of the front end
* Add some help text so the client knows that that field is for (explain it is for that pdf link)

**Comment by qingxin-yuan** [comment]
Resolved by Colin!
Cheers

**Comment by rcass** [comment]
Looks much better. I would tweak the to something a bit more succinct link "Upload economic report for economic benefits section."

**Comment by colinmj** [comment]
Done!
