### ISSUE TITLE
Front-page.php: Use Dynamic Tags for Title and Tag line

### ISSUE THREAD

**Issue by rcass** [redacademy/sosnpr-fall-2017#14]
Change this static code:
![screen shot 2017-12-14 at 2 51 10 pm](https://user-images.githubusercontent.com/5028555/34018377-6d30299a-e0de-11e7-9007-a1aee3adccac.png)
 To something more dynamic using WP template tag, use the site title and tag line 👍

**Comment by michaelujkim** [comment]
used get_bloginfo for both. thanks

**Comment by rcass** [comment]
Looks good! Just tweak the indentation to make things more readable and it would be golden 👌
