### ISSUE TITLE
Double check that img have alt tags

### ISSUE THREAD

**Issue by rcass** [redacademy/sosnpr-fall-2017#15]
Ran the front page page source through HTML validation and a few images were missing alt attributes
![screen shot 2017-12-14 at 2 56 25 pm](https://user-images.githubusercontent.com/5028555/34018531-14c1ab34-e0df-11e7-8454-45b5383d0550.png)

**Comment by michaelujkim** [comment]
all images have alt test.

**Comment by rcass** [comment]
Looks like that has been resolved 👍
