### ISSUE TITLE
Front Page: Remove stay </img> tag

### ISSUE THREAD

**Issue by rcass** [redacademy/sosnpr-fall-2017#18]
Images are self closing elements so there is not need for this tag, just delete.
![screen shot 2017-12-15 at 11 52 27 am](https://user-images.githubusercontent.com/5028555/34058126-ba009984-e18e-11e7-9d07-bf2f84cd0c6d.png)

**Comment by qingxin-yuan** [comment]
Issue resolved! 
Cheers

**Comment by rcass** [comment]
Awesome looks resolved 👍
