### ISSUE TITLE
Front Page: Remove unnecessary alt on div

### ISSUE THREAD

**Issue by rcass** [redacademy/sosnpr-fall-2017#19]
While checking another issue, found this one, where a div has an alt attribute added to it. This is makes it invalid so please just remove.

![screen shot 2017-12-15 at 11 55 03 am](https://user-images.githubusercontent.com/5028555/34058200-f51bc1a6-e18e-11e7-985f-53e2af6fe9a4.png)

**Comment by qingxin-yuan** [comment]
Issue resolved!
Cheers
