### ISSUE TITLE
Add clarity and Helper text to Custom Fields

### ISSUE THREAD

**Issue by rcass** [redacademy/sosnpr-fall-2017#20]
Since there are so many helper fields on this website, it has great potential for becoming unclear and confusing to the user.

To avoid possible confusion and possible friction:
* Use proper casing on labels - Make the first letter on each work Uppercase (helps with readability)
* Add helper text for fields - Ex: 'Text for the Reports section' , Make them short and clear
* Ensure custom field are listed in the same order as the visual page

**Comment by qingxin-yuan** [comment]
Finished!

Cheers
