### ISSUE TITLE
Front Page: <a> can't be nested in a <button>

### ISSUE THREAD

**Issue by rcass** [redacademy/sosnpr-fall-2017#21]
Validation error to fix:
![screen shot 2017-12-15 at 11 55 03 am](https://user-images.githubusercontent.com/5028555/34064967-2bc393fa-e1b2-11e7-82bd-3162cde9e251.png)

**Comment by qingxin-yuan** [comment]
Would this be a wrong screenshot? 
however, <button> is now deleted on the front page. 

Cheers
