### ISSUE TITLE
Header.php: Remove Google Font Link and Enqueue scripts

### ISSUE THREAD

**Issue by rcass** [redacademy/sosnpr-fall-2017#22]
https://github.com/redacademy/sosnpr-fall-2017/blob/2fc84c34a2e44b751c038f18d172285d3eb0dc37/themes/sosnpr/header.php#L15

WordPress works different that your typical html/css wed site, remember you must enqueue to add scripts and styles to the head. 

Refer back to slides or just use some google fu too look up how to enqueue in wordpress

**Comment by qingxin-yuan** [comment]
Resolved - fonts are now enqueued in functions.php
Cheers
