### ISSUE TITLE
Wigetized Area Confusion: 'sidebar' in footer

### ISSUE THREAD

**Issue by rcass** [redacademy/sosnpr-fall-2017#3]
The widgetized setup you have is very confusing.

Here are the two big issues:
* For the user, in the backend of WP it says 'Sidebar' but really items appear in the footer.
* Sidebar.php is not being using at all (all the code is commented out), but called in many templates (get_sidebar).

Some suggestions:
* Make the back end of WP say footer not sidebar, so aka register the sidebar as footer. If you look in functions.php, that is where that widgized area is registered and where you will change some things. Then update all the calls to that widgetzed area, basically in the code it should be clear you are calling a widgetized area called footer.
* If there are absolutely no sidebars, just get rid of sidebar.php and all the calls to the template.

**Comment by ambrosiae** [comment]
Hi Rose,
I just changed the name of Sidebar to Footer in the backend of WP through functions.php. I didn't change the id because it stopped working when I did but I could probably figure it out if it's important. Thanks! :D

**Comment by ambrosiae** [comment]
Hi Rose,
I just changed the name of Sidebar to Footer in the backend of WP through functions.php. I didn't change the id because it stopped working when I did but I could probably figure it out if it's important. Thanks! :D

**Comment by rcass** [comment]
Yep it will make things easier to follow in the for the client and for other developers trying to follow your code.

For more info about this about widgetized areas check [this](https://developer.wordpress.org/themes/functionality/sidebars/#registering-a-sidebar) out

Also just close this once this issue is resolved!

**Comment by ambrosiae** [comment]
Done!

**Comment by rcass** [comment]
Ticket is half way done. Good job renaming the widgetized area.

Now, just need to cleanup sidebar related code. For example you are not using sidebar.php and there are `get_sidebar();` calls in your template files.  Think about do these need to be there? Are they doing anything? What will happen if I remove them?

If the answer is that they serve no purpose in your custom theme, best to delete them 

Along with the codex, [this](https://wordpress.stackexchange.com/questions/82016/what-is-the-difference-with-get-sidebar-and-dynamic-sidebar) may also be helpful in answering those questions

**Comment by ambrosiae** [comment]
Done :D

**Comment by ambrosiae** [comment]
Done (I hope)! :D

**Comment by ambrosiae** [comment]
Done! (I hope) :D

**Comment by rcass** [comment]
I am still seeing commented out code in sidebar.php and get_sidebar tags. I am not seeing any changes in github related to what I just mentioned. 

What was the solution you came to?
Can you verify that github reflects that solution?

Right now the issue is still present

**Comment by ambrosiae** [comment]
Sorry, fixed it in Develop but didn't push it to Master. Pushed to the master branch just now!

**Comment by rcass** [comment]
Perfect looks resolved now!
