### ISSUE TITLE
Remove the sos_assets folder from git

### ISSUE THREAD

**Issue by rcass** [redacademy/sosnpr-fall-2017#5]

**Comment by michaelujkim** [comment]
removed all unnecessary photos and images from assets folder. the pictures that are left are used in the code

**Comment by michaelujkim** [comment]
got rid of all images and files not used in the code

**Comment by rcass** [comment]
Just walking through the folder, just a few questions:

- [x] Logo: I searched the code, I can't see where those are being used.
- [x] home-page: Only one image is being used in this folder (/south-okanagan-grasslands.jpg) the rest are not being called in the theme.
- [x] photos-section: Nothing from this folder is getting called in the theme
- [x] proposed-park: Only `horse-riding-near-mt-kobau-quarter.jpg` and `horse.jpg` are being used by theme, the rest are not called.
- [x] resources: `similkameen-river-bend-dam-quarter.jpg` is the only one used


Seems like changes were still getting made when I was checking so some of the points above have been resolved.

**Comment by rcass** [comment]
Some of the UI icons, can be replaced with code:
- [x] For the hamburger: Use [this](http://fontawesome.io/icon/bars/)
- [ ] Angles: More CSS practice, but use [this](http://fontawesome.io/icon/angle-right/) icon with a some css to create the look that you want. If you [browse the icons](http://fontawesome.io/icons/) there are more varieties, so you can choose what matches best.
