### ISSUE TITLE
Remove Divs for Divider lines

### ISSUE THREAD

**Issue by rcass** [redacademy/sosnpr-fall-2017#7]
Found this 
```        
<div class="divider-line">
        </div>
```
in about-us.php. Very unnecessary. Try using border bottom and/or elements that exist on the page to get the desired css. A div with no info init, you should def try to avoid.

So just make sure to remove all those unneccessary divs.

**Comment by rcass** [comment]
Found some more in resources.php

```
       <div class="borders"></div>
```

**Comment by ambrosiae** [comment]
Thanks!

**Comment by rcass** [comment]
Looks lots of those empty divs have been removed! Yay
