### ISSUE TITLE
Use of Section tags

### ISSUE THREAD

**Issue by rcass** [redacademy/sosnpr-fall-2017#8]
In about-us.php, use of the section tags just for the divider is a bit incorrect.
The block of code that look like this:
```
      <section class="divider">
        <a href="#top" class="scroll-up">
        <i class="fa fa-angle-up" aria-hidden="true"></i>
        </a>
      </section>
```
Are not really true sections, since they do not hold any content. 

From MDN:
> The HTML <section> element represents a standalone section — which doesn't have a more specific semantic element to represent it — contained within an HTML document. Typically, but not always, sections have a heading.

Since these are used for just css, a non semantic element such a div is actually better suited to this. Also are those divs really necessary though? Seem like you could style them without that extra markup (just place that a and i icon within the corresponding li element)

**Comment by colinmj** [comment]
Done!
